cli: fix TestContractInitAndCompile test
Problem:
```
C:\Users\Anna\AppData\Local\Temp\TestContractInitAndCompile620446590\001\testcontract\main.go:1:10: expected ';', found ':' (and 8 more errors)
error while trying to compile smart contract file: couldn't load packages due to errors:
--- FAIL: TestContractInitAndCompile (0.13s)
    executor_test.go:197:
                Error Trace:    executor_test.go:197
                                                        contract_test.go:124
                Error:          Received unexpected error:
                                error while trying to compile smart contract file: couldn't load packages due to errors:
                Test:           TestContractInitAndCompile
```

Solution:
Use filepath.Base() instead of path.Base() to get the contract name during initialisation.